# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lzb56XTHhJL7rhEpy4OF0HhMDjgf1STH
"""

# Copyright 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

import numpy as np
import subprocess
import pickle
import torch
import os
from torch.utils.data import TensorDataset

mnist_path = "mnist.npz"


# URL from: https://github.com/fchollet/keras/blob/master/keras/datasets/mnist.py
if not os.path.exists(mnist_path):
    subprocess.call("wget https://s3.amazonaws.com/img-datasets/mnist.npz", shell=True)


f = np.load('mnist.npz')
x_tr = torch.from_numpy(f['x_train'])
y_tr = torch.from_numpy(f['y_train']).long()
x_te = torch.from_numpy(f['x_test'])
y_te = torch.from_numpy(f['y_test']).long()
f.close()

torch.save((x_tr, y_tr), 'mnist_train.pt')
torch.save((x_te, y_te), 'mnist_test.pt')


train_dataset = TensorDataset(x_tr, y_tr)
train_loader = torch.utils.data.DataLoader(train_dataset,
    batch_size=32, shuffle=True, sampler=None,
    num_workers=4, pin_memory=True)


test_dataset = TensorDataset(x_te, y_te)
test_loader = torch.utils.data.DataLoader(test_dataset,
    batch_size=32, shuffle=True, sampler=None,
    num_workers=4, pin_memory=True)